/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Timer_1.h"
#include "QuadDec_1.h"
#include "QuadDec_1_PVT.h"
#include "isr_1.h"
#include "QuadDec_2.h"
#include "QuadDec_2_PVT.h"
#include "quad_A_pendulo_aliases.h"
#include "quad_A_pendulo.h"
#include "quad_B_pendulo_aliases.h"
#include "quad_B_pendulo.h"
#include "quad_A_motor_aliases.h"
#include "quad_A_motor.h"
#include "quad_B_motor_aliases.h"
#include "quad_B_motor.h"
#include "Pin_ENA_aliases.h"
#include "Pin_ENA.h"
#include "PWM_Motor.h"
#include "BUS_CLK.h"
#include "Pin_IN1_aliases.h"
#include "Pin_IN1.h"
#include "Pin_IN2_aliases.h"
#include "Pin_IN2.h"
#include "UART_1.h"
#include "QuadDec_1_isr.h"
#include "QuadDec_1_Cnt16.h"
#include "QuadDec_2_isr.h"
#include "QuadDec_2_Cnt16.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

